### ISSUE TITLE
[Epic] Making local development great again

### ISSUE THREAD

**Issue by Demonsthere** [Orcpub/orcpub#6]
Collection of tasks that need to be done, to have a easy to develop and maintain deployment mechanism:

- [x] Database initialisation on docker image build or app startup -> #5
- [x] Docker-compose pulls all images required -> #8 
- [x] Documentation is updated to reflect the docker setup -> #9
